import { HealthEnvironmentData } from '../../types';

export const mockHealthData: HealthEnvironmentData[] = [
  // Add about 100 entries of mock data here
  {
    _id: '1',
    userId: 'user1',
    basicHealthId: 'health1',
    environmentalId: 'env1',
    scoresId: 'score1',
    timestamp: '2023-05-01T12:00:00Z',
    steps: 8000,
    heartRate: 72,
    weight: 70,
    height: 175,
    location: { type: 'Point', coordinates: [-73.935242, 40.730610] },
    activityLevel: 'moderate',
    regionId: 'region1',
    cityId: 'city1',
    areaId: 'area1',
    temperature: 22,
    humidity: 60,
    airQualityIndex: 50,
    uvIndex: 5,
    noiseLevel: 45,
    latitude: 40.730610,
    longitude: -73.935242,
    respiratoryRate: 14,
    oxygenSaturation: 98,
    activeEnergyBurned: 300,
    cardioHealthScore: 85,
    respiratoryHealthScore: 90,
    physicalActivityScore: 80,
    environmentalImpactScore: 75,
    nearestCity: 'New York',
    onBorder: [],
    country: 'United States',
    continent: 'North America',
    airQualityDescription: 'Moderate',
    uvIndexDescription: 'Moderate',
    noiseLevelDescription: 'Normal',
    bmi: 22.9,
    environmentalImpact: 'Low',
    airQuality: 'Good',
  },
  // ... add more mock data entries ...
];