//constants/httpStatus.ts

// OVERALL SYSTEM ERROR CHECKS


export enum HttpStatus {
  OK = 200,
  CREATED = 201,
  BAD_REQUEST = 400,
  UNAUTHORIZED = 401,
  FORBIDDEN = 403,
  NOT_FOUND = 404,
  METHOD_NOT_ALLOWED = 405,
    TOO_MANY_REQUESTS = 429,
    INVALID_LOG_FORMAT = 406,
  INTERNAL_SERVER_ERROR = 500,
  SERVICE_UNAVAILABLE
}


// OVERALL SYSTEM ERROR CHECKS
export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  METHOD_NOT_ALLOWED: 405,
  INVALID_LOG_FORMAT: 406,
  INTERNAL_SERVER_ERROR: 500,
  TOO_MANY_REQUESTS: 429,
} as const;
